my:
   greeting: Hello World from config server (ONLINE GITHUB)
   list:
      values: One, Two, Three, Four, Five
db:
   conection: connection-string-here-from-config-server
   host: localhost
   port: 1200
message= Message From Server (HOSAM)
response = Response From Server
