my:
   greeting: Hello World from config server (ONLINE GITHUB)
   list:
      values: One, Two, Three, Four, Five
db:
   conection: connection-string-here-from-config-server
   host: localhost
   port: 1200
message: Message From Server (***HOSAM - GITHUB***)..... NEW NEW * 3
response: Response From Server (***HOSAM - GITHUB***) ..... NEW
secretData: {cipher}c182fb349ea22148f470b9f032ddbb15a42bfe9d82c7a3487ae414417ee252a7
